# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
print(np.show_config)

1.19.5
<function show at 0x0000016634CF1E50>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
z=np.zeros(10)
print(z)
print(len(z))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [14]:
arr=np.zeros((4,4))
print(arr.size)
print(arr.itemsize)

16
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [21]:
np.info('size')

     *** Found in numpy ***
 size(*args, **kwargs)

Return the number of elements along a given axis.

Parameters
----------
a : array_like
    Input data.
axis : int, optional
    Axis along which the elements are counted.  By default, give
    the total number of elements.

Returns
-------
element_count : int
    Number of elements along the specified axis.

See Also
--------
shape : dimensions of array
ndarray.shape : dimensions of array
ndarray.size : number of elements in array

Examples
--------
>>> a = np.array([[1,2,3],[4,5,6]])
>>> np.size(a)
6
>>> np.size(a,1)
3
>>> np.size(a,0)
2
----------------------------------------------------------------------------

     *** Repeat reference found in numpy.core *** 
     *** Found in numpy.ma ***
 size(obj, axis=None)

Return the number of elements along a given axis.

Parameters
----------
a : array_like
    Input data.
axis : int, optional
    Axis along which the elements are counted.  By default, give
    the total number of eleme

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [25]:
vec=np.arange(10,49)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [26]:
rev_vec=vec[::-1]
rev_vec

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [30]:
mat=np.arange(0,9)
print(mat)
mat.reshape(3,3)

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [32]:
arr1=np.array([1,2,0,0,4,0])
np.nonzero(arr1)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [36]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [38]:
x=np.random.random((3,3,3))
print(x)

[[[0.43307837 0.37887635 0.5894954 ]
  [0.05683195 0.21647444 0.26648385]
  [0.44374766 0.44810097 0.49458672]]

 [[0.70610631 0.50595329 0.07082599]
  [0.11334275 0.74503641 0.32558854]
  [0.933386   0.55341082 0.93559076]]

 [[0.39156304 0.60947786 0.13443316]
  [0.78652643 0.88161054 0.43388346]
  [0.31197334 0.86405792 0.60243827]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [41]:
x=np.random.random((10,10))
print(x)
x_min=x.min()
print("minimum number")
print(x_min)
x_max=x.max()
print("maximum number")
print(x_max)


[[0.22586908 0.22723    0.24350326 0.15348297 0.72301013 0.42100462
  0.99050772 0.39020806 0.56097588 0.47321398]
 [0.57836786 0.31061055 0.31046308 0.59976419 0.15513565 0.20648825
  0.13086016 0.49395352 0.37766907 0.77394182]
 [0.64391378 0.18339091 0.46052795 0.92798971 0.99371624 0.66149375
  0.01909739 0.81912883 0.3363998  0.62071386]
 [0.33840952 0.792385   0.54280325 0.60401821 0.239699   0.45743302
  0.66795575 0.6725259  0.70463441 0.02066929]
 [0.30933901 0.93034652 0.75759927 0.06616228 0.55207819 0.47497193
  0.37665233 0.4426875  0.76117385 0.7599531 ]
 [0.90842695 0.95414045 0.30813916 0.85453811 0.52649181 0.65782231
  0.0414321  0.315528   0.9547341  0.95346271]
 [0.45543374 0.55336573 0.61170192 0.26413456 0.78410004 0.21102733
  0.7351551  0.30333488 0.5550414  0.21918304]
 [0.69594916 0.74145464 0.8402273  0.18410676 0.59405235 0.99418292
  0.24661467 0.8672369  0.87455706 0.12376641]
 [0.90759475 0.69564177 0.74381567 0.80075251 0.60529435 0.45206251
  0.84699132

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [42]:
x=np.random.random(30)
print(x)
print("Mean")
print(x.mean())

[0.24848308 0.01213477 0.17362211 0.42104925 0.86102705 0.9489979
 0.2554507  0.59530413 0.36401322 0.31103673 0.77736954 0.27268151
 0.49521653 0.92524268 0.6527573  0.86961602 0.35031981 0.87012205
 0.0608059  0.9186678  0.40539414 0.89640473 0.15643036 0.61336705
 0.94223475 0.22690537 0.12166267 0.33491652 0.11024635 0.53894949]
Mean
0.49101431792987105


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [47]:
x=np.ones((6,6))
print(x)
x[1:-1, 1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [48]:
x=np.ones((6,6))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [55]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [61]:
print(np.diag(1+np.arange(4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [67]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [71]:
x= np.array([[0,1], [1,0]])
x = np.tile(x,(4,4))
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [72]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
norm_x= (x-xmin)/(xmax-xmin)
print (norm_x)

[[0.94072368 0.67586747 0.         0.44824239 0.98877902]
 [0.72829565 0.76795827 0.03323841 0.87238179 0.82739692]
 [0.46474175 0.57742073 0.90864228 0.17790202 0.18026514]
 [1.         0.42709881 0.31668525 0.86982561 0.42362458]
 [0.74956412 0.85340901 0.95930746 0.20580272 0.39269125]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [73]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-73-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [79]:
x=np.random.random((5,3))
print(x)
y=np.random.random((3,2))
print(y)
Z=np.dot(x,y)
print("Product of x and y")
print(Z)

[[0.42962969 0.13473796 0.97366275]
 [0.85806583 0.56073086 0.45471098]
 [0.22961114 0.18517278 0.51846133]
 [0.49429556 0.95769431 0.68640492]
 [0.47469014 0.44438634 0.50698657]]
[[0.73584463 0.72061138]
 [0.1779519  0.61047411]
 [0.88010518 0.47247105]]
Product of x and y
[[1.19704321 0.85187754]
 [1.13137975 1.17548146]
 [0.65821048 0.52346156]
 [1.13825678 1.26514904]
 [0.87457909 0.85288996]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [76]:
x=np.arange(10)
print(x)
x[(3<x)&(x<8)]*=-1
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [77]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [86]:
print(Z**Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[[1.24022601 0.87234821]
 [1.14987719 1.20930918]
 [0.75935665 0.71260193]
 [1.15881963 1.34655614]
 [0.88940323 0.87309064]]
[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[[0.+1.19704321j 0.+0.85187754j]
 [0.+1.13137975j 0.+1.17548146j]
 [0.+0.65821048j 0.+0.52346156j]
 [0.+1.13825678j 0.+1.26514904j]
 [0.+0.87457909j 0.+0.85288996j]]
[[1.19704321 0.85187754]
 [1.13137975 1.17548146]
 [0.65821048 0.52346156]
 [1.13825678 1.26514904]
 [0.87457909 0.85288996]]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [87]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-87-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-87-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [91]:
x=random.uniform(-10,+10,10)
x

array([-7.73385484, -5.34707461, -8.22401517,  9.28358917, -7.75835984,
        0.81057819,  7.18779383,  2.6620458 , -7.22883294, -9.76244014])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [92]:
x=np.arange(5)
y=np.arange(3,9)
print(np.intersect1d(x,y))

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [105]:

np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)





[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [106]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [110]:
print("today")
today=np.datetime64('today','D')
print(today)

print("yesterday")
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(yesterday)

print("tomorrow")
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(tomorrow)

today
2021-11-16
yesterday
2021-11-15
tomorrow
2021-11-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [114]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [117]:
A = np.ones(5)
B = np.ones(5)
C = np.ones(5)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [125]:
Z = np.random.uniform(0,5,5)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[3.07636106 3.24750406 4.54156996 1.35171209 4.8442897 ]
[3. 3. 4. 1. 4.]
[3. 3. 4. 1. 4.]
[3. 3. 4. 1. 4.]
[3 3 4 1 4]
[3. 3. 4. 1. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [127]:
x=np.zeros((5,5),dtype=int)
x+=np.arange(5)
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [128]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [132]:
z=np.linspace(0,1,12,endpoint=True)[1:-1]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [133]:
x=np.random.random(10)
x.sort()
x

array([0.18608261, 0.2636897 , 0.44654511, 0.5831237 , 0.5880849 ,
       0.64447377, 0.78167933, 0.83598905, 0.95351387, 0.98291666])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [134]:
z=np.arange(5)
np.add.reduce(z)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array_equal)

In [138]:
x=np.random.randint(1,2,5)
y=np.random.randint(4,7,8)
print(np.array_equal(x,y))

x=np.random.randint(1,2,5)
y=np.random.randint(1,2,5)
print(np.allclose(x,y))


False
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [139]:
z=np.zeros(10)
z.flags.writeable=False
z[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [140]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
R=np.sqrt(x**2+y**2)
T=np.arctan2(y,x)
print(R)
print(T)

[0.72371603 1.21346975 0.44277011 1.09933863 0.52797662 0.55534035
 0.88678765 0.72296364 1.11459228 0.26276146]
[0.0928495  0.83324131 0.17398495 0.47196838 1.54685831 1.55323114
 0.6631033  1.34867611 0.79778134 0.72879279]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [143]:
z=np.random.random(10)
z[z.argmax()]=0
z

array([0.00956568, 0.01215601, 0.27981142, 0.87453781, 0.7514852 ,
       0.43853133, 0.62168488, 0.40201983, 0.37648555, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [144]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [148]:
X = np.arange(10)
Y = X + 2.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

-0.004910349004560856


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [151]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print(" ")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
 
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [156]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [158]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

57


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [159]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-159-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [160]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.94428833 0.2150881  0.89507484 0.85351187 0.94461908
  0.45612045 0.64921801 0.3685058  0.31881827]
 [0.94428833 0.         0.7556276  0.07346321 0.45825843 0.157887
  0.49259126 0.7953423  0.66328653 0.62666187]
 [0.2150881  0.7556276  0.         0.70028442 0.74889058 0.73998111
  0.26364777 0.65368822 0.15724444 0.16868162]
 [0.89507484 0.07346321 0.70028442 0.         0.48909844 0.11096331
  0.4397379  0.79748369 0.60004924 0.58040458]
 [0.85351187 0.45825843 0.74889058 0.48909844 0.         0.5999747
  0.54462211 0.40650543 0.75035973 0.58021304]
 [0.94461908 0.157887   0.73998111 0.11096331 0.5999747  0.
  0.49047147 0.90134565 0.62162281 0.63919883]
 [0.45612045 0.49259126 0.26364777 0.4397379  0.54462211 0.49047147
  0.         0.59313991 0.2083654  0.15193752]
 [0.64921801 0.7953423  0.65368822 0.79748369 0.40650543 0.90134565
  0.59313991 0.         0.73918233 0.51930995]
 [0.3685058  0.66328653 0.15724444 0.60004924 0.75035973 0.62162281
  0.2083654  0.73918233

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [161]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [163]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [165]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print(" ")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [166]:
n = 15
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [168]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.05016159 -0.18104247 -0.3372728   0.33686524 -0.19324167 -0.18176159
  -0.09809753  0.43416415 -0.19051004  0.36073513]
 [-0.37396314  0.31320142  0.14857176  0.43202173  0.20853077  0.21124604
  -0.3267393  -0.15939875 -0.46078191  0.00731137]
 [ 0.21679924 -0.34384115  0.08667645 -0.41412249 -0.06703458  0.20069024
  -0.02184111  0.29554988  0.38186203 -0.33473851]
 [-0.07313741  0.54077579 -0.18647689 -0.09717194 -0.39865643  0.42466235
  -0.20874427  0.23215772 -0.24726426  0.01385534]
 [ 0.10805858 -0.35248216 -0.56816619  0.36327316  0.19785307  0.27887683
  -0.25278196  0.26949151  0.18604172 -0.23016457]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [169]:
Z = np.random.randint(0,15,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[ 1  7 10]
 [13  0  0]
 [ 4  2  9]]
[[13  0  0]
 [ 4  2  9]
 [ 1  7 10]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [170]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [171]:
Z = np.random.uniform(0,1,10)
print(Z)
x = 0.5
m = Z.flat[np.abs(Z - x).argmin()]
print(m)

[0.43748213 0.43007314 0.93822566 0.00168676 0.66639209 0.72795501
 0.23746643 0.15880961 0.74507007 0.17152515]
0.4374821341119981


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [172]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [173]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [174]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[5. 2. 6. 3. 4. 2. 2. 4. 1. 1.]
[ 9.  3. 11.  5.  7.  3.  3.  7.  1.  1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [176]:
X = [1,2,3,4]
I = [1,3,9,3]
F = np.bincount(I,X)
print(F)

[0. 1. 0. 6. 0. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [177]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [178]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[37 46 40 39]
 [62 60 55 46]
 [31 57 59 50]]
[[37 46 40 39]
 [62 60 55 46]
 [31 57 59 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [179]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.54842954 0.45374743 0.58265596 0.59253973 0.47048083 0.62074938
 0.37828977 0.61904829 0.49391012 0.41220799]
0    0.548430
1    0.453747
2    0.582656
3    0.592540
4    0.470481
5    0.620749
6    0.378290
7    0.619048
8    0.493910
9    0.412208
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [180]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.70634224, 1.11852589, 0.78733661, 1.52284479, 1.13329989])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [183]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*(3))
Z0[::4] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [184]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [188]:
A = np.arange(9).reshape(3,3)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [189]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 7, 11) ( 7, 20) ( 7, 40) ( 7, 57) ( 7, 76) ( 7, 87) ( 7, 88) ( 7, 89)
 (11, 19) (11, 26) (11, 40) (13, 37) (13, 67) (19, 26) (20, 76) (23, 32)
 (23, 90) (25, 33) (25, 98) (32, 90) (33, 98) (37, 67) (41, 46) (41, 47)
 (46, 47) (57, 87) (63, 69) (63, 84) (69, 84) (88, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [190]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [191]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(10)
print(moving_average(Z, n=3))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [193]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [195]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)



array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [196]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.6806495 , -0.12152962,  0.89217184, -0.1633621 , -0.31927547,
        0.92732711,  0.81832493,  0.22298765,  0.7586643 , -0.52630593,
        0.23503362, -0.9087338 ,  0.69484112, -0.90528546, -0.95704665,
        0.00552839, -0.17857529,  0.73621826,  0.34269193, -0.08790031,
        0.47928714,  0.39717936, -0.48138565,  0.10638109,  0.28176424,
        0.53621264, -0.84451353,  0.72755101, -0.10481679, -0.79740379,
        0.83870609,  0.96542578, -0.7450322 ,  0.02158487, -0.07249787,
       -0.75564088, -0.64816283, -0.80507304, -0.09804052, -0.72286662,
       -0.60772802,  0.63003402, -0.53943095,  0.9103887 , -0.48935972,
        0.15096263, -0.20205583, -0.0942753 ,  0.97361601,  0.40911578,
        0.39988081, -0.75082868,  0.55356757,  0.70608123, -0.82241341,
       -0.42685766,  0.76441575,  0.7094705 ,  0.10911982,  0.12708443,
       -0.18944293, -0.28427566,  0.10076901,  0.72323024,  0.1811916 ,
       -0.75146991, -0.55747424,  0.15606471, -0.0368832 ,  0.72

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [197]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.09505956  9.23137003  4.92972862  0.81454165  7.7499848   1.57425189
  3.71145297  3.35960809  2.8059127  13.52057743]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [198]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[17.74905776  0.79887639  0.53176694  1.61650043 10.89859412  0.41295893
   2.57326367 12.55749075 10.63249247  7.01821817]
 [10.26008618  4.35643288  7.7394147   1.88926389  3.02657304  0.15546219
   1.78856159  4.27317979  6.21055047  0.91814642]
 [12.05602865  7.61979908  8.11670356  5.1643311   4.43446938  3.52425043
   5.47522627  4.95143739  9.43101046  1.47856779]
 [17.53219261  0.19760863  0.69615868  2.21914491 10.752743    1.04562352
   1.95199011 12.54144917 10.13488651  7.50190265]
 [13.1975531   7.54246794  7.12259034  5.09481327  5.58017825  3.90757933
   5.98997159  6.06641464 10.34899917  0.9846691 ]
 [10.42846644  7.83872807  0.60540667 10.30261548  4.61596196 11.1726381
   8.49007672  8.31020292  0.04713676 12.41431791]
 [13.20254111  4.76379755  0.06080853  7.20926766  7.01981904  7.27550683
   4.46617591  9.98267767  3.89580834 10.55535617]
 [ 5.77331232  0.83223071  8.49677796  3.32915013  0.8363145   6.65433464
   4.90263981  1.63655601  0.27971438  4.12667156]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [199]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 3 8 8 1 8 3 8 3 1]
 [7 3 0 6 2 3 5 7 4 4]
 [5 2 4 0 3 2 4 6 8 4]
 [8 3 5 1 0 2 4 8 6 3]
 [8 3 9 8 2 1 3 4 6 0]
 [7 4 4 3 5 6 4 9 1 5]
 [6 6 0 4 7 0 9 4 6 3]
 [3 6 9 4 8 1 4 9 2 9]
 [9 6 9 0 9 3 8 6 6 8]
 [5 9 5 9 9 9 3 7 1 6]]
[[0 0 0 0 0]
 [0 9 3 8 8]
 [0 7 3 0 6]
 [0 5 2 4 0]
 [0 8 3 5 1]]


<ipython-input-199-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [200]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [201]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [203]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [204]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 1]
   [2 1 0]
   [2 0 4]]

  [[4 1 4]
   [1 0 1]
   [0 4 4]]

  [[1 4 3]
   [0 1 2]
   [4 4 1]]

  [[4 3 3]
   [1 2 2]
   [4 1 3]]

  [[3 3 4]
   [2 2 3]
   [1 3 3]]

  [[3 4 2]
   [2 3 0]
   [3 3 0]]

  [[4 2 0]
   [3 0 2]
   [3 0 1]]

  [[2 0 4]
   [0 2 4]
   [0 1 3]]]


 [[[2 1 0]
   [2 0 4]
   [1 2 3]]

  [[1 0 1]
   [0 4 4]
   [2 3 3]]

  [[0 1 2]
   [4 4 1]
   [3 3 1]]

  [[1 2 2]
   [4 1 3]
   [3 1 2]]

  [[2 2 3]
   [1 3 3]
   [1 2 0]]

  [[2 3 0]
   [3 3 0]
   [2 0 0]]

  [[3 0 2]
   [3 0 1]
   [0 0 2]]

  [[0 2 4]
   [0 1 3]
   [0 2 3]]]


 [[[2 0 4]
   [1 2 3]
   [1 4 3]]

  [[0 4 4]
   [2 3 3]
   [4 3 4]]

  [[4 4 1]
   [3 3 1]
   [3 4 1]]

  [[4 1 3]
   [3 1 2]
   [4 1 1]]

  [[1 3 3]
   [1 2 0]
   [1 1 0]]

  [[3 3 0]
   [2 0 0]
   [1 0 4]]

  [[3 0 1]
   [0 0 2]
   [0 4 4]]

  [[0 1 3]
   [0 2 3]
   [4 4 2]]]


 [[[1 2 3]
   [1 4 3]
   [2 1 1]]

  [[2 3 3]
   [4 3 4]
   [1 1 4]]

  [[3 3 1]
   [3 4 1]
   [1 4 2]]

  [[3 1 2]
   [4 1 1]
   [4 2 3]]

  [[1 2 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [205]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6 12  3 10]
 [ 6  2  5  7  4]
 [12  5  5 42 14]
 [ 3  7 42  4 11]
 [10  4 14 11  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [207]:
p, n =5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [208]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [209]:
def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [211]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[95 96 97 98 99]
[99 97 95 96 98]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [212]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [213]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(4e8)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [218]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [219]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 4 0]
 [3 4 2]
 [3 0 0]
 [1 4 2]
 [4 2 1]
 [0 4 1]
 [4 4 0]
 [3 3 4]
 [1 2 3]
 [0 1 0]]
[[0 4 0]
 [3 4 2]
 [3 0 0]
 [1 4 2]
 [4 2 1]
 [0 4 1]
 [4 4 0]
 [3 3 4]
 [1 2 3]
 [0 1 0]]
[[0 4 0]
 [3 4 2]
 [3 0 0]
 [1 4 2]
 [4 2 1]
 [0 4 1]
 [4 4 0]
 [3 3 4]
 [1 2 3]
 [0 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [220]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [221]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [222]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.1438487 , 0.27786928, 0.2268098 , 0.06079385, 0.19872334,
        0.3347394 , 0.27072606, 0.16718334, 0.44908209, 0.08376836],
       [0.20299447, 0.3921198 , 0.32006639, 0.08579024, 0.28043171,
        0.47237302, 0.38203953, 0.23592353, 0.63372959, 0.1182111 ],
       [0.05335723, 0.10306895, 0.08412966, 0.02255002, 0.07371166,
        0.12416356, 0.10041935, 0.06201266, 0.16657624, 0.03107187],
       [0.1880464 , 0.36324496, 0.2964974 , 0.07947283, 0.25978133,
        0.4375885 , 0.35390697, 0.21855063, 0.58706312, 0.10950629],
       [0.05626255, 0.10868109, 0.08871055, 0.02377788, 0.07772529,
        0.13092431, 0.10588721, 0.06538927, 0.17564638, 0.03276374],
       [0.15119224, 0.29205463, 0.23838854, 0.0638974 , 0.20886826,
        0.351828  , 0.28454674, 0.17571813, 0.47200794, 0.08804477],
       [0.12652599, 0.24440739, 0.19949666, 0.05347286, 0.17479246,
        0.29442904, 0.23812438, 0.1470506 , 0.39500223, 0.07368071],
       [0.00453486, 0.00875989, 0.0071502

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [223]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [224]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.187527    0.18200536]
